name: dart_ntp
description: This is simple NTP server with offers offset feature. This may helped test system based on time.
version: 1.0.1
repository: https://github.com/grzesl/DartNTP

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  udp: ^5.0.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
